### ISSUE TITLE
FlxUISpriteButton doesn't automatically resize

### ISSUE THREAD

**Issue by Arcnor** [HaxeFlixel/flixel-ui#45] opened 2014-03-19 07:18 UTC
Ok, this one might have something to do with my understanding/expectations with this class:

When I create a FlxUISpriteButton and I add a "big" image, let's say 200x100, the size of the button is still a very small one (i.e. like creating an FlxUIButton with no text). I was expecting the button to take the size of my image (and I'm doing that right now calling `resize` after I create the button, but still...)

Also, when clicking on the button, I still see the old graphic below my button (I see a like with 1px height on top of it).

If it's just that my expectations are too much, you can safely close this :)

**Comment by larsiusprime** [comment] 2015-01-19 18:12
Closing for now until I get an update about what the issue is.

**Closed by larsiusprime** 2015-01-19 18:12 UTC
